version: '3.7'

services:
  
  postgres:
    image: postgres
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      - './sql/backend.sql:/docker-entrypoint-initdb.d/backend.sql'
    environment:
      POSTGRES_USER: 'polkastats'
      POSTGRES_PASSWORD: 'polkastats'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U polkastats']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    # 
    # https://pgtune.leopard.in.ua/#/
    #
    # Optimized for:
    #
    # DB Version: 13
    # OS Type: linux
    # DB Type: web
    # Total Memory (RAM): 128 GB
    # CPUs num: 12
    # Connections num: 200
    # Data Storage: ssd

    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=32GB"
      - "-c"
      - "effective_cache_size=96GB"
      - "-c"
      - "maintenance_work_mem=2GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=41943kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=12"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=12"
      - "-c"
      - "max_parallel_maintenance_workers=4"

  

#
# Persistent volumes
#
volumes:
  db-data: {}
